apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites-pvc
  namespace: frappe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: frappe-storage
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: frappe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: frappe-storage
  resources:
    requests:
      storage: 2Gi